spring.application.name=boot

# ??a ch? c?a kho l?nh: jdbc:postgresql://[??a_ch?_máy]:[c?ng]/[tên_database]
spring.datasource.url=jdbc:postgresql://localhost:5432/spring_boot_test 

# Tên b?o v? gi? c?a (th??ng m?c ??nh là postgres)
spring.datasource.username=postgres

# M?t kh?u m? c?a kho (c?u thay b?ng m?t kh?u pgAdmin c?a c?u nhé)
spring.datasource.password=vietanh2k5

# Yêu c?u Spring hi?n câu l?nh SQL ra màn hình console ?? c?u d? debug (ki?m tra l?i)
spring.jpa.show-sql=true

# Không ?? Spring t? ??ng s?a ??i b?ng trong DB (vì mình ?ã t?o b?ng file SQL ? trên r?i)
spring.jpa.hibernate.ddl-auto=update